import React from 'react'
import Head from 'next/head'
import StoriesContent from '@/container/StoriesContent'
import NavBar from '@/components/NavBar'

const StoriesPage = () => {
    return (
        <>
            <Head>
                <title>Duong Thanh Toan</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon5.ico" />
            </Head>
            <main>
                <NavBar />
                <StoriesContent />
            </main>
        </>
    )
}
export default StoriesPage;
